unbind C-b
unbind '"'
unbind %
unbind c

# Do not rename windows automatically
set-option -g allow-rename off

# Enabling mouse support
set -g mouse on

# Prefix is now Control + A
set-option -g prefix C-a
bind-key C-a send-prefix

# Split planes are now | and -
bind | split-window -h
bind - split-window -v

# Create a new window
bind n new-window
bind w kill-window

# Reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Switch between panes using vim motions without prefix
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# DESIGN

# Copy mode
setw -g mode-style 'fg=black bg=red bold'

# Status bar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'

set -g status-left ''
set -g status-left-length 10

set -g status-right ''
set -g status-right-length 10

setw -g window-status-current-style 'fg=black bg=colour245'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=colour245 bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=colour245]#F '

setw -g window-status-bell-style 'fg=yellow bg=red bold'

# messages
set -g message-style 'fg=colour245 bg=black'
