decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10

    # Change transparency of focused and unfocused windows
    active_opacity = 1
    inactive_opacity = 0.85

    blur {
        enabled = true
        size = 8
        passes = 5
        new_optimizations = true
        noise = 0.0117
        contrast = 0.8916
        brightness = 0.8172
        popups = true
        xray = true
    }

}
