general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 2
    gaps_out = 5
    # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    border_size = 0
    col.active_border = 0x00000000
    col.inactive_border = 0x00000000

    layout = dwindle
}
