-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        gaps_in = 0,
        gaps_out = 0,
        -- col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
        border_size = 0,
        layout = "dwindle",
        col = {
            active_border = "0x00000000",
            inactive_border = "0x00000000",
        },
    },
})
