-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
    input = {
        kb_layout = "latam",
        follow_mouse = 0,
        accel_profile = "flat",
        -- force_no_accel = true
        touchpad = {
            disable_while_typing = false,
            natural_scroll = true,
            scroll_factor = 0.2,
        },
    },
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more

hl.device({
    name = "epic mouse V1",
    sensitivity = 0,
})
