-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- See https://wiki.hyprland.org/Configuring/Monitors/

--

-- Monitor configuration for dynamic switching

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

-- Dual monitor example on G15 Strix

-- eDP-1 is the built in monitor while DP-1 is external

-- Both monitors here are at 1440 and 165Hz

-- DP-1 is on the left and  eDP-1 is on the right

--monitor=DP-1,2560x1440@165,0x0,1

--monitor=eDP-1,2560x1440@165,2560x0,1
