# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# rules below would make the specific app transparent
windowrule {
  name = windowrule-1
  opacity = 1 1
  match:class = ^(kitty)$
}

# Games
windowrule {
  name = windowrule-2
  tag = +game
  match:class = Minecraft 1.8.9
}

windowrule {
  name = windowrule-3
  tag = +game
  match:class = Lunar*
}

windowrule {
  name = windowrule-4
  tag = +game
  match:title = Lachy
}

windowrule {
  name = windowrule-5
  tag = +game
  match:class = Badlion Minecraft Client*
}

# Game Launchers
windowrule {
  name = windowrule-6
  tag = +game
  match:class = lunarclient
}

windowrule {
  name = windowrule-7
  tag = +game
  match:class = .*steam.*
}

windowrule {
  name = windowrule-8
  tag = +game
  match:title = Steam
}

windowrule {
  name = windowrule-9
  tag = +game
  match:class = Badlion Client
}

windowrule {
  name = windowrule-10
  tag = +game
  match:class = io-github-gaming32-modloadingscreen-ActualLoadingScreen
}

# Terminal
windowrule {
  name = windowrule-11
  tag = +terminal
  match:class = .*kitty.*
}

# Browser
windowrule {
  name = windowrule-12
  tag = +browser
  match:class = .*brave.*
}

windowrule {
  name = windowrule-13
  tag = +browser
  match:class = Brave-browser
}

# Chat
windowrule {
  name = windowrule-14
  tag = +chat
  match:class = vesktop
}

windowrule {
  name = windowrule-15
  tag = +fakefullscreen
  match:class = Whatsapp*
}

# Develop
windowrule {
  name = windowrule-16
  tag = +develop
  match:class = Code
}

windowrule {
  name = windowrule-17
  tag = +develop
  match:class = dev.zed.Zed
}

windowrule {
  name = windowrule-18
  tag = +develop
  match:class = .*code.*
}

windowrule {
  name = windowrule-19
  tag = +develop
  match:class = .*jetbrains.*
}

# Misc
windowrule {
  name = windowrule-20
  tag = +fakefullscreen
  match:class = Spotify*
}

windowrule {
  name = windowrule-21
  tag = +misc
  match:class = Twitter
}

# Important
windowrule {
  name = windowrule-22
  tag = +important
  size = (monitor_w*0.5) (monitor_h*0.5)
  match:class = org.keepassxc.KeePassXC
}

windowrule {
  name = windowrule-23
  tag = +important
  match:class = org.pulseaudio.pavucontrol
}

windowrule {
  name = windowrule-24
  tag = +important
  match:class = blueman-manager
}

# Rules
windowrule {
  name = windowrule-25
  workspace = 1
  match:tag = terminal
}

windowrule {
  name = windowrule-26
  workspace = 2
  match:tag = browser
}

windowrule {
  name = windowrule-27
  workspace = 3
  match:tag = chat
}

windowrule {
  name = windowrule-28
  workspace = 4
  match:tag = develop
}

windowrule {
  name = windowrule-29
  workspace = 8
  immediate = on
  no_blur = on
  match:tag = game
}

windowrule {
  name = windowrule-30
  workspace = 9
  fullscreen_state = 0 2
  match:tag = misc
}

windowrule {
  name = windowrule-31
  stay_focused = on
  center = on
  float = on
  match:tag = important
}

windowrule {
  name = windowrule-32
  fullscreen_state = 0 2
  match:tag = fakefullscreen
}

windowrule {
  name = windowrule-33
  maximize = on
  match:tag = dev
}

windowrule {
  name = windowrule-34
  suppress_event = maximize
  match:class = .* # You'll probably like this.
}

# PiP
windowrule {
  name = windowrule-35
  float = on
  pin = on
  move = ((monitor_w*0.67)) ((monitor_h*0.72))
  size = (monitor_w*0.33) (monitor_h*0.28)
  rounding = 0
  no_blur = on
  match:title = ^(Picture in picture)$
}
