-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- rules below would make the specific app transparent

hl.window_rule({
    name    = "windowrule-1",
    match   = {
        class = "^(kitty)$",
    },
    opacity = "1.0",
})

-- Games

hl.window_rule({
    name  = "windowrule-2",
    match = {
        class = "Minecraft 1.8.9",
    },
    tag   = "+game",
})

hl.window_rule({
    name  = "windowrule-3",
    match = {
        class = "Lunar*",
    },
    tag   = "+game",
})

hl.window_rule({
    name  = "windowrule-4",
    match = {
        title = "Lachy",
    },
    tag   = "+game",
})

hl.window_rule({
    name  = "windowrule-5",
    match = {
        class = "Badlion Minecraft Client*",
    },
    tag   = "+game",
})

-- Game Launchers

hl.window_rule({
    name  = "windowrule-6",
    match = {
        class = "lunarclient",
    },
    tag   = "+game",
})

hl.window_rule({
    name  = "windowrule-7",
    match = {
        class = ".*steam.*",
    },
    tag   = "+game",
})

hl.window_rule({
    name  = "windowrule-8",
    match = {
        title = "Steam",
    },
    tag   = "+game",
})

hl.window_rule({
    name  = "windowrule-9",
    match = {
        class = "Badlion Client",
    },
    tag   = "+game",
})

hl.window_rule({
    name  = "windowrule-10",
    match = {
        class = "io-github-gaming32-modloadingscreen-ActualLoadingScreen",
    },
    tag   = "+game",
})

-- Terminal

hl.window_rule({
    name  = "windowrule-11",
    match = {
        class = ".*kitty.*",
    },
    tag   = "+terminal",
})

-- Browser

hl.window_rule({
    name  = "windowrule-12",
    match = {
        class = ".*brave.*",
    },
    tag   = "+browser",
})

hl.window_rule({
    name  = "windowrule-13",
    match = {
        class = "Brave-browser",
    },
    tag   = "+browser",
})

-- Chat

hl.window_rule({
    name  = "windowrule-14",
    match = {
        class = "vesktop",
    },
    tag   = "+chat",
})

hl.window_rule({
    name  = "windowrule-15",
    match = {
        class = "Whatsapp*",
    },
    tag   = "+fakefullscreen",
})

-- Develop

hl.window_rule({
    name  = "windowrule-16",
    match = {
        class = "Code",
    },
    tag   = "+develop",
})

hl.window_rule({
    name  = "windowrule-17",
    match = {
        class = "dev.zed.Zed",
    },
    tag   = "+develop",
})

hl.window_rule({
    name  = "windowrule-18",
    match = {
        class = ".*code.*",
    },
    tag   = "+develop",
})

hl.window_rule({
    name  = "windowrule-19",
    match = {
        class = ".*jetbrains.*",
    },
    tag   = "+develop",
})

-- Misc

hl.window_rule({
    name  = "windowrule-20",
    match = {
        class = "Spotify*",
    },
    tag   = "+fakefullscreen",
})

hl.window_rule({
    name  = "windowrule-21",
    match = {
        class = "Twitter",
    },
    tag   = "+misc",
})

-- Important

hl.window_rule({
    name  = "windowrule-22",
    match = {
        class = "org.keepassxc.KeePassXC",
    },
    tag   = "+important",
    size  = { "(monitor_w*0.5)", "(monitor_h*0.5)" },
})

hl.window_rule({
    name  = "windowrule-23",
    match = {
        class = "org.pulseaudio.pavucontrol",
    },
    tag   = "+important",
})

hl.window_rule({
    name  = "windowrule-24",
    match = {
        class = "blueman-manager",
    },
    tag   = "+important",
})

-- Rules

hl.window_rule({
    name      = "windowrule-25",
    match     = {
        tag = "terminal",
    },
    workspace = 1,
})

hl.window_rule({
    name      = "windowrule-26",
    match     = {
        tag = "browser",
    },
    workspace = 2,
})

hl.window_rule({
    name      = "windowrule-27",
    match     = {
        tag = "chat",
    },
    workspace = 3,
})

hl.window_rule({
    name      = "windowrule-28",
    match     = {
        tag = "develop",
    },
    workspace = 4,
})

hl.window_rule({
    name      = "windowrule-29",
    match     = {
        tag = "game",
    },
    workspace = 8,
    immediate = true,
    no_blur   = true,
})

hl.window_rule({
    name             = "windowrule-30",
    match            = {
        tag = "misc",
    },
    workspace        = 9,
    fullscreen_state = "0 2",
})

hl.window_rule({
    name         = "windowrule-31",
    match        = {
        tag = "important",
    },
    stay_focused = true,
    center       = true,
    float        = true,
})

hl.window_rule({
    name             = "windowrule-32",
    match            = {
        tag = "fakefullscreen",
    },
    fullscreen_state = "0 2",
})

hl.window_rule({
    name     = "windowrule-33",
    match    = {
        tag = "dev",
    },
    maximize = true,
})

hl.window_rule({
    name           = "windowrule-34",
    match          = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- PiP

hl.window_rule({
    name     = "windowrule-35",
    match    = {
        title = "^(Picture in picture)$",
    },
    float    = true,
    pin      = true,
    move     = { "((monitor_w*0.67))", "((monitor_h*0.72))" },
    size     = { "(monitor_w*0.33)", "(monitor_h*0.28)" },
    rounding = 0,
    no_blur  = true,
})
