-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'











-- source = ~/.config/hypr/conf/monitors.conf -> requires manual conversion
local monitors = require("conf.monitors")
-- TODO: convert ~/.config/hypr/conf/monitors.conf to .lua and use require()

-- source = ~/.config/hypr/conf/input.conf -> requires manual conversion
local input = require("conf.input")
-- TODO: convert ~/.config/hypr/conf/input.conf to .lua and use require()

-- source = ~/.config/hypr/conf/general.conf -> requires manual conversion
local general = require("conf.general")
-- TODO: convert ~/.config/hypr/conf/general.conf to .lua and use require()

-- source = ~/.config/hypr/conf/misc.conf -> requires manual conversion
local misc = require("conf.misc")
-- TODO: convert ~/.config/hypr/conf/misc.conf to .lua and use require()

-- source = ~/.config/hypr/conf/decoration.conf -> requires manual conversion
local decoration = require("conf.decoration")
-- TODO: convert ~/.config/hypr/conf/decoration.conf to .lua and use require()

-- source = ~/.config/hypr/conf/render.conf -> requires manual conversion
local render = require("conf.render")
-- TODO: convert ~/.config/hypr/conf/render.conf to .lua and use require()

-- source = ~/.config/hypr/conf/animations.conf -> requires manual conversion
local animations = require("conf.animations")
-- TODO: convert ~/.config/hypr/conf/animations.conf to .lua and use require()

-- source = ~/.config/hypr/conf/dwindle.conf -> requires manual conversion
local dwindle = require("conf.dwindle")
-- TODO: convert ~/.config/hypr/conf/dwindle.conf to .lua and use require()

-- source = ~/.config/hypr/conf/master.conf -> requires manual conversion
local master = require("conf.master")
-- TODO: convert ~/.config/hypr/conf/master.conf to .lua and use require()

-- source = ~/.config/hypr/conf/window-rules.conf -> requires manual conversion
local window_rules = require("conf.window-rules")
-- TODO: convert ~/.config/hypr/conf/window-rules.conf to .lua and use require()

-- source = ~/.config/hypr/conf/binds.conf -> requires manual conversion
local binds = require("conf.binds")
-- TODO: convert ~/.config/hypr/conf/binds.conf to .lua and use require()

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.layer_rule({
    match = {
        namespace = "waybar",
    },
    blur = true,
})

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1200",
    position = "0x0",
    scale    = 1,
})

-- workspace = 1, monitor:HDMI-A-1

-- workspace = 2, monitor:eDP-1

-- workspace = 3, monitor:eDP-1

-- workspace = 4, monitor:HDMI-A-1

--

hl.window_rule({
    name             = "fl-all-float",
    match            = {
        class = "^(fl64.exe)$",
    },
    float            = true,
    no_initial_focus = true,
})

hl.window_rule({
    name             = "fl-tooltip-1",
    match            = {
        class = "^(fl64.exe)$",
        title = "^tooltip$",
    },
    float            = true,
    no_initial_focus = true,
})

hl.window_rule({
    name             = "fl-confirm",
    match            = {
        class = "^(fl64.exe)$",
        title = "^Confirm$",
    },
    float            = true,
    no_initial_focus = true,
})

hl.window_rule({
    name             = "fl-subwindow-1",
    match            = {
        class = "^(fl64.exe)$",
        title = "^$",
    },
    float            = true,
    no_initial_focus = true,
})

hl.window_rule({
    name             = "fl-subwindow-bg",
    match            = {
        class = "^(fl64.exe)$",
        title = "^$",
    },
    float            = true,
    no_initial_focus = true,
    workspace        = "special:fl-bg silent",
})

hl.window_rule({
    name  = "fl-main",
    match = {
        class = "^(fl64.exe)$",
        title = "^(FL Studio 2025)$",
    },
    float = false,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("~/.config/hypr/scripts/xdg-portal-hyprland.sh")
    hl.exec_cmd("~/.config/hypr/scripts/battery-monitor.sh")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("[[ -f ~/.config/hypr/readmode_state ]] && gammastep -O 4500")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("waybar")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("awww img ~/.config/hypr/wallpaper.jpg")
end)
